### ISSUE TITLE
01-gcm-web-push-notifications-watchify command always runing

### ISSUE THREAD

**Issue by atom992** [couchbaselabs/Couchbase-by-Example#4]
I am following "Couchbase-by-Example/01-gcm-web-push-notifications/01-gcm-web-push-notifications.md" at line 67:
    $ watchify ./src/app.js -o ./dist/bundle.js
but no response for a long time. 
and when I check the ./dist/bundle.js file, the file size is 925528 with 33516 line.
and I found the log shows [the reg ID is ::] at line 53043 from:
https://camo.githubusercontent.com/dfdcf495468a4db5cd41cce44ec43edd322c7529/687474703a2f2f636c2e6c792f696d6167652f3158314233623362304633302f53637265656e25323053686f74253230323031352d30362d3133253230617425323031362e32312e32382e706e67

**Comment by jamesnocentini** [comment]
watchify is sort of like a filewatcher development tool so the output may be a larger size as a result.
Also, it's bundling all the dependencies in one file (pouchdb, pouchdb-find, browserify).

I'm not sure why you don't get the registration token logged in the console.
A couple questions:
Which browser are you using?
Are you logged in as a user in Chrome?

**Comment by atom992** [comment]
I have  generated working bundle.js file and get the notifications in the chrome, through the watchify command still running. 
btw, on my mac, the bundle.js file size is 925525 with 33516 line.

and,  when you generated the Server API key, you also should enable APIs(APIs and Auth -> APIs, Enabled APIs), and enabled Google Cloud Messaging for Android under Mobile APIs.
or you will get 401 error when you send a POST request to the GCM server.

**Comment by jamesnocentini** [comment]
@atom992 Glad you fixed it. Added the missing content in the markdown file. Thanks for pointing this out!
